version: '3.3'

volumes:
  foodhelper_static_volume:
  foodhelper_media_volume:
  foodhelper_db_volume:

services:
  backend:
    container_name: foodhelper-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - foodhelper_static_volume:/app/backend_static/
      - foodhelper_media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    container_name: foodhelper-db
    image: postgres:15.2-alpine3.17
    restart: always
    volumes:
      - foodhelper_db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    container_name: foodhelper-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodhelper-nginx
    image: nginx:1.19.3
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodhelper_static_volume:/var/html/backend_static/
      - foodhelper_media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
