version: '3.3'
services:
  db:
    image: postgres:13.4
    container_name: foodhelper-db
    volumes:
      - foodhelper_db_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: martiandrew/foodhelper_backend
    restart: always
    volumes:
      - foodhelper_static_volume:/app/backend_static/
      - foodhelper_media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    image: martiandrew/foodhelper_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - foodhelper_static_volume:/var/html/backend_static/
      - foodhelper_media_volume:/var/html/media/
    depends_on:
      - backend

volumes:
  foodhelper_static_volume:
  foodhelper_media_volume:
  foodhelper_db_volume:
