name: Main Foodhelper Workflow
# Перечень событий-триггеров, при которых должен запускаться workflow
on:
  push:
    branches:
      - master
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      - name: Print project
        run: tree .
